### ISSUE TITLE
NYT extra entry was temporarily gone after sychronization with a second device

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#1]
I had an additional "NYTimes Article" entry on **one** device [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1OWpRYWI0MkVkREk). But after Synchronizing with the other device, this entry was gone on **both** devices.
[Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1dGZ1UUwtS1dCMWM)

After restarting the app on both phones, the entry was back on **both** devices.

### Expected behavior
After synchronizing the data, the entry should be there immediately on both devices, and should not require a restart of the app. Or at least it should not disappear on the device which had the entry even before the sync.

**Comment by dankito** [comment]
For sure an indexing (not a database) problem.
Priorizing it down, working on that later.

**Comment by dankito** [comment]
This was quite a stupid bug. Synchronization worked fine, simply forgot to update favorites after synchronization.
