### ISSUE TITLE
Empty entry can be saved

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#11]
It is currently possible to save an empty entry (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1THVxc1pkS3NHUFk))

### Expected behavior
- A new entry that is empty is not saved (either show a warning, disable the save button when entry is empty or simply discard the entry)
- Also consider an existing (valid) entry that is edited by the user by deleting all content, title, tags. When the user presses the save button, this entry should then basically deleted, or the user should not be able to save it when everything is empty

**Comment by dankito** [comment]
- You're absolutely right, the save button should be disabled when there's nothing to save.

- Also true about the second point. Will also disable the save button (or show a delete button) when all data of an entry is deleted.

**Comment by dankito** [comment]
Both should be fixed / implemented now
