### ISSUE TITLE
More intelligent pre-selection of the icon to use for a new URL-source

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#12]
Currently, it seams that not the "best" available icon is pre-selected when the user wants to add a new URL-source. 
But in case of www.computerbase.de ([Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1d1hRZk5ZbEtFV00)), there are the following icons available:
- 16x16 (too small!)
- 180x180 (perfect!)
- 1280x720 (too large! And not square!) [pre selected]

Other example: NYTimes
- only 250x40 [pre selected]
I honestly would not use such a wide icon (use square icons as a convention), so in this case we could crop the icon in the middle

Other example: sz.de
- 16x16 (too small! why even list this one when there are so many alternatives?)
- 32x32 [pre selected]
- 57x57
- 72x72 (I would say this one would be a better default than 32x32)
- 114x114
- 144x144

### Expected behavior
The user should not pick the best icon out of many bad icons:
- Preselect the best icon available
- Use square icons as default selection only (if available)
- In case there are many icons available, get rid of the very small, way too large or non-square icons

**Comment by dankito** [comment]
You're right in all respects.
Did it as you suggested.
(Also found a way to find more icons for sites like NYTimes.)
