### ISSUE TITLE
Advanced text-editor for Title/Abstract or References is overkill and has bad performance

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#13]
The advanced (markdown?) text-editor is also used when the user wants to edit the Title/Abstract or the References of an entry. This has the following downsides:
- The editor can take long to load (sometimes it took up to 3 seconds on my Nokia 5, most of the time it is quick)
- The user might get overwhelmed with options that are not useful
  - I guess nobody uses text formating, images search options in the Title/Abstract/References, which is usually just half a sentence long
  - When using the options of the advanced text editor (add URL, ...), the editor does not really seem to be mobile friendly (vertical scrolling necessary)
  - The user cannot just enter/edit the text inline (the advanced editor opens in a new full-screen page)

### Proposed solution
Only use the advance editor in the Information (the main content), but use a normal EditText view for the references and title/abstract?

**Comment by dankito** [comment]
The Reference is an extra entity (you can also set an url, publishing date etc. on it).

But for the abstract/title you definenately got a point.
Actually i also wanted to model it as a plain text (would have been way less effort to me *g*). The reason why i went the html path is, some newspaper sites like Süddeutsche use rich text elements in their abstracts like bullets / unordered list, hyperlinks, italic, bold, ...
But maybe i convert these rare cases to plain text and spare me a lot of effort for all other cases.

**Comment by dankito** [comment]
Asked now two persons and both said that formatting options are absolutely unnecessary for the title or abstract.
Will convert it to plain text in next version.

**Comment by dankito** [comment]
Did it as suggested.
In current release title/abstract is edited directly in EditEntryActivity.
