### ISSUE TITLE
Unexpected behavior when floating action button show sub-entries

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#14]
When the floating action button is pressed (either on the home page or in the entry's edit page), the only option to close it is to press the floating button again. I'm not sure if this is the default Google metro design behavior...

### Expected behavior
I would expect the following, when the floating button was pressed and the sub-buttons are shown:
- When I use the BACK-button of the phone, the sub-buttons are closed, instead of navigating back or closing the app
- When I tap in the backgroud, I would expect that the sub-butons are closed, instead of selecting and navigating to the items  whatever I pressed in the background.

**Comment by dankito** [comment]
Even though there is no default Material Design behaviour - as the default Floating Action Button is only a button, it doesn't show a sub menu when being clicked - it sounds to me feasible anyway.

Implementing the back button behaviour should be quite easy, but close it by clicking somewhere in the background may be quite tough.

**Comment by dankito** [comment]
Found a way to also close menu on touches outside of floating action button.
