### ISSUE TITLE
After opening and closing some inner-links in a newarticle: loading of web contet gets slower and slower

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#15]
I could figure out a problem that the loading of the web content takes longer and longer after using lots of links withing the web content

### Steps to reproduce:
- Add a new news artice from any source (I used the guardian)
- Select any artice
- Check: The web content loads and renders usually quickly (aber 1-2 seconds)
- Repeatedly: click an a link of the web content, and navigate back using the BACK button (do this about 5-10 times)
- Now go back and select the same or another artice
- Check The web content now takes long to load and render (10-15 seconds)

**Comment by b3nk4n** [comment]
One time the web content was even not rendered anymore, so I had to restart the app. After the app restart, it was working perfectly again.

**Comment by dankito** [comment]
Actually it was intended that the app doesn't react to clicks on links at all but routes the user to the browser.
But for loading web sites that do internal re-directing a had to overwrite that behaviour till the page is fully loaded. After the page is fully loaded clicks are routed to browser again.
Will have to find a way to disable clicks during page loading. Low prio.

**Comment by dankito** [comment]
'Solved' it by disabling link handling during a page load.
(After page has loaded default Android link handling is enabled again = user gets redirected to web browser.)
