### ISSUE TITLE
Adding multiple tags of a new entry seems to be effortful

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#16]
It looks like it is just possible to add one tag at a time, but **not** multiple tags by seperating them with space, komma or semicolon. Actually I thought there was even a toast-message explaining that I can seperate them by comma, but as soon as I use a comma, there is no "New" button anymore and I cannot add the new tags (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1YVpSNy1VSzRfZU0)).

Also, after a tag was added, the text-field is not cleared. Hence, when I want to add multiple tags, I have to do the following:
1. Enter a tag name
2. Press "New"
3. Press backspace multiple times to delete it
4. Enter second tag name
5. Press "New" again
6. Press (again) backspace multiple times
7. ...

### Expected behavior
I would like to enter "Tag1, Tag2, Tag3" or "Tag1; Tag2, Tag3;Tag4" and when I press the back button, these tags are then generated if not already there. Or when I press "New" that at least all these tags are generated.

**Comment by dankito** [comment]
The comma was intended to select multiple **existing** tags.
If you have already created Tag1 and Tag2, entering 'Tag1, Tag2' and pressing either the Toggle/Tauschen button or 'Enter' on keyboard will select Tag1 and Tag2.

So why did i disable creating tags separated by comma?
As during tests i sometimes misspelled a tag name, let's say i entered 'Ta**h**1, Tag2'. Then unintentionally a new tag Tah1 gets created and mostly you don't see it (as i simply double press enter quickly on the keyboard an am done with tags editing without re-checking for result).

But you're for sure right, creating tags is currently tedious. What do you think about displaying an inline message 'Tag(s) Tah1 does not exist, would you like to create it?' So it would be on more click for the user and there's no unintentional creation of tags.
And when entered only not existing tags (like in your example), i can create them directly.

**Comment by dankito** [comment]
Fixed it now. Both is now possible: Create multiple comma separated tags and mixing existing and not existing tags. In latter case a notification is shown to ask the user if she/he likes to create the not existing tags

**Comment by b3nk4n** [comment]
Will test it later.
One thing that just pop's into my mind: Use [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) algorithm to find similar tags, like you mentioned before: "Did you mean 'Tag1' instead of 'Tag 1'?"
