### ISSUE TITLE
Read later entries: "Save" option might be misleading

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#18]
Entries in the "Read Later" section have an option to "Save" the artice. This means that the article is moved to the "Entries" section. But isn't "Save" misleading here, because the article was already saved in order to read it later.

### Proposal
Personally, I thought the save button was a bug at first. Especially after the artice was "gone" after pressing "Save". Ok, it was **not** gone but moved to the "Entries" section, but since I was still in the "Read Later" section, the first thing that I thouht was "Hmm, why is the article gone now after saving?".
So, my proposal would be to call this command "Remember", "Keep" (dt: Merken, Behalten) or anything like that.

**Comment by dankito** [comment]
You're right, this confuses users.
Will discuss how to name it properly.

**Comment by dankito** [comment]
As we simply couldn't find a good name to signal user 'Pressing this button will move article from ReadLaterArticles to Entries' we agreed that first time user saves a ReadLaterArticle we show an info dialog with message, that article has been moved to entries.
Do you think that's ok that way?

**Comment by b3nk4n** [comment]
-  How about "Keep" instead of "Save"?
- I'm not sure, but how about the icon used in the "Entries" section instead of the Save-disk icon, to give a visual connection that pressing this is related to the Entries section?

**Comment by b3nk4n** [comment]
Actually I would rename it like the following:
- Save ==> Keep (or Remember)
- Delete ==> Forget

This naming matches perfectly to your app title "Deep**Thought**"! =)

**Comment by dankito** [comment]
Yeah, that's not bad (also the idea with the Entries icon).
Going to re-think about this.

**Comment by dankito** [comment]
I'm using now the same icon as for Items, but we decided to keep as text Save / Delete.
