### ISSUE TITLE
"Reader View" toggle should indicate its current state

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#19]
In the edit mode of a single artice, the user is able to switch between 2 different reader view modes:
- browser view (Web-Ansicht?)
- content view (Inhalts-Ansicht, Text-Ansicht?)

But it is not clear in which view-state we currently are in, because the button always shows the same icon and text "Reader view"

### Expected behavior
The button should be a toggle which shows either:
- in which state we are currently in (using different text and icons)
- or: in which state it will change when the button is pressed ("in Web-Ansicht wechseln", "to Web-View")

**Comment by dankito** [comment]
Absolutely right.

Which of the two options you listed do think is more apropriate?
There are reasons for both and i cannot decide which one to choose?

**Comment by dankito** [comment]
Implemented now first option.
Will check what others say with tonight's build.

**Comment by b3nk4n** [comment]
I think both options have its pros and cons. The important thing here is that there is at least any kind of state indication ;-)

**Comment by b3nk4n** [comment]
Is the button gone now? I cannot find any option to toggle the view state anymore at least ;-)

**Comment by dankito** [comment]
No, it should still be there, but of course only for newspaper articles (as only for those it's needed to show the original website first). It will appear after the page has fully loaded (now with animated indicator * g *).
Did you encounter newspaper articles where the button didn't show up?

**Comment by b3nk4n** [comment]
Ok no I found it now! :) Works as expected!
