### ISSUE TITLE
NYTimes creates a new Add-entry, but other sources do not

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#2]
For me it is not clear why NYTimes (feed: nytimes.com) does create a new entry [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1OWpRYWI0MkVkREk), but other sources (The Guardian, Zeit) do not.

### Expected behavior
Either all sources do create an entry, or none of them? Or when a special source creates such an entry, there I would expect an explaination with this source did so, but others don't. What is special about this source? And do I really want this "Add button" for this source?

### Related questions
What happens if I add many sources that create such a button? Is there a chance of a layout overflow?

**Comment by b3nk4n** [comment]
Ah! Now I got it 💃 
It was added because I added it to my favorites (using the **star**)

**Comment by b3nk4n** [comment]
Haha, I guessed right! A layout overflow!
See [Screenshot ](https://drive.google.com/open?id=0BxICpnwLMG_1VHp6U1c1UXdDR2s):)

**Comment by dankito** [comment]
Didn't get the last one. Is there still an issue (or is it just that you have too many favorites for you too small display *g*)?
Can i close it?

**Comment by b3nk4n** [comment]
> or is it just that you have too many favorites for you too small display?

Exactly! Since you can calculate the required size of N items, and you are able to figure out the users screen size, you could limit the number of favorites to add.

**One exception**
I case your have one big device and one small device and use the offline-sync, then it might be tough ;-)
I don't know what would be the limit of the smallest screen possible, or at least a 720p display, but I think limiting the favorites to 5-6 items would be worth a thought at least. Or make them smaller when you have more? But well, just a suggestion... ;-)

**Comment by dankito** [comment]
I think i'm going to leave it that way. It's the user's responsibility (and freedom *g*) to add that amount of favorites as large as her/his display is.
And exactly, during synchronization tests i encountered exactly the issue you described: On one device more favorites fit the screen size than on the other. Really going to leave it to the user's hand how many favorites she/he wants to set.

**Comment by b3nk4n** [comment]
The **overflow** is even more likely when the phone is used in **wide-screen** mode:
[Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1Rlp3VThVMHRvTkk)
