### ISSUE TITLE
Search textfield is hardly visible

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#25]
The serach textfield is hardly visible, especially the caret is almost no contrast to the background (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1SnZ3eDRMNndiZUE)).

### Proposal
Use a White background for the Search-box, as it is done in some other Android apps:
[Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1UTNfdEYweWlDUms)

**Comment by dankito** [comment]
Fixed it by setting caret's color to white (did a little hack via reflection *g*).

If you think also hint's and search result's text color should be set to white for better contrast, i also can do that.

**Comment by b3nk4n** [comment]
Using the WHITE caret is good enough I think. It's now much more obvious and its blinking takes the users attention.
