### ISSUE TITLE
Bug in delete item from the Reference section

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#26]
I just faced a strange behavior in the Reference section. I simply wanted to delete all items, so I started with the first item (swipe to left, press delete), but nothing happend, I tried to delete the second item, which was deleted successfully. But when I tried to delete the first item again, I was not able to swipe the items to the left, nor could I press the item (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1T3RJZlZyamF1Vnc)).
Then, I tried to restart the app, but when I navigated to the Reference section, the item was strangely visualized (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1VDFTemRqYnQtYnM)). After navigating to another section (Entries) and back, the Items was back, but I still could not press/swipe to delete it.

**Comment by dankito** [comment]
Damn, for a reason i could not figure out yet the TestFairy (my crash analytics tool) app token got removed from last build. Therefore TestFairy didn't record anything and i cannot see your log files.
You don't have the application logs for this bug at your hand, don't you?

**Comment by dankito** [comment]
I can explain the phenomenon you are seeing pretty well:
Deleting the reference from database worked fine, but then an error occurred before the reference could get removed from index.
Therefore the search results still contain the reference with id xyz, but querying that id from database returns null, as there it doesn't exist anymore. So you are seeing an empty list item for this reference.

**Comment by dankito** [comment]
Still couldn't figure out the reason for this bug, but at least i implemented some 'auto healing' for it:
An minute after app start all deleted entities since last index update get now queried from database and then kicked out from index.

**Comment by dankito** [comment]
Ah, i think i found the cause of this issue.
Couldn't find it that long as should already be solved by a change from october 5th. So in current version it shouldn't occur anymore. Deleted a lot of references and all well so far *g*.
