### ISSUE TITLE
The mysterious "Plus button list item"

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#29]
I'm not sure if I already created such a task, but I sill don't get what the Plus-Button ([Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1U1ZDUVNmQ1k5ZHc)) is about?

At least...
- I cannot click it
- It feels like it sometimes there, sometimes not?!?

**Comment by dankito** [comment]
I think this is related to #26 and it should be the reference during that's deletion an error occurred.
But it should show an empty list item than, not the plus icon or the chevron. Fixed that now.
