### ISSUE TITLE
Edit with multiple selected items opens all selected items in sequence

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#3]
When I select multiple items in the "Entries" list, and select "Edit", all selected items will be opened on top of each other (in random order?), and the BACK button then just closes this item and leads to the next one, instead back to the home page.

### Steps to reproduce
1. Select 2 entries A and B (long hold)
2. Select "Edit"
3. See: you only see item A in edit mode (I expected to edit common things in both, such as tags for both entries at once)
4. Close the item A that is currently in edit mode
5. Now item B is in edit mode (I expected to get back to the home activity)

## Expected behavior
I thought I could edit common properties at once when selecting two items, such as add tag for both entries. But I had to to that one after another.
In my opinion, editing them one after another is not a good idea. So either I would only allow to edit the fields that effect both items at once, or would **not** show the edit option  when >1 item is selected.

**Comment by dankito** [comment]
This is by design, it just means: Start batch editing of all selected entries. So you don't have to edit the first one, return to the entries list, search for and select the second one, edit it, return, search for the next one, ...

Do you think it's an big issue not having an option to edit common properties of multiple entries?

Going to ask other users for their view on this.

**Comment by dankito** [comment]
Also asked two others on this issue and both said that editing common properties of multiple entries is not necessary (as it almost never happens that two entries have the same tags or the same abstract).
Will close this now and set it to 'Won't fix'.

**Comment by b3nk4n** [comment]
Yes,
I think editing common features is not very important. But I also don't think that batch-editing makes that much sense. But, well, it's already implemented, so just leave it as it is ;-)
