### ISSUE TITLE
Rich text editor: hard to interact

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#33]
I personally have some problems using the rich text editor. Some examples:

- double tapping a word to selected it
  - sometimes it gets selected
  - sometimes it opens the keyboard and the word is not selected
- tapping an option from the tools bar (font style, ...)
  - sometimes it opens a dropdown, so that I can select whatever I want
  - sometimes the dropdows is closed immediately

All in all, the richt text editor is not very mobile friendly and feels like an embadded website. Mayber there is an alternative for this component? I personally would be very happy about an editor with markdown support :)

**Comment by dankito** [comment]
He, he, well recognized * g *.
Yes, i actually just embed a JavaScript html editor and yes, it's not mobile ready, actually the docs state that is doesn't even run on Android * g *.
When i first started the project, which is now three years ago, there was not html, mark down or other rich text editor for Android. So i decided to go the embedded html editor way.
A quick look around figured out, that there are now some Android (and JavaFX as well) mark down editors. And as the HTML Editor also gets me on my nerves, may really going to replace it in the next release.

**Comment by dankito** [comment]
Ok, as this is really important, i already did it for this version (even though that i am aware of that this will introduce a lot of new bugs and feature requests * g *).
Kicked out the JavaScript html editor and using a native RichText editor now.
