### ISSUE TITLE
Title/Abstract changes not saved when textbox still in focus

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#34]
**Steps to reproduce:**
1. Create a new entry
2. Enter some content
3. Add a title
4. Enter some text for the title
5. Immediately press "save" (or apply?) without closing the keyboard or doing anything else (so that the textbox is still in focus)
6. The new entry has no title (or sometimes just the first letter?)

I'm quite sure that you save to changes ( to your temporary edit model) only when the texbox looses its focus. Had the same issue once with my own note taking app ;-)

**Comment by dankito** [comment]
You think you're sure and can be sure about that * g *.
It really just as a listener, if there has been any changed compared to it's original value -> Save button is shown or not.
And then it gets the actual value when the focus is lost. Right, that's a bug. (Behaviour was correct before when editing was done in an extra dialog.)

**Comment by dankito** [comment]
Fixed it now.
