### ISSUE TITLE
Entry items: did title and reference changed positions?

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#35]
I just realized that in the entry-list page, the title (bold) that is shown is the title of the reference, but not the title of the note ([Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1TWcwMENIcVA4NXM)).

Most note taking apps have have items that consist of title + content. But here, the reference seems to be the most important part (because it is bold). But even that it is highlightes that much, it is just an optional field.

Personally, I would:
- List the title first (bold)
- Show the first lines of the content (thin)
- Show the reference / tags last (small and thin)

**Comment by dankito** [comment]
Same here: Behaviour was correct before a changed the field to title / summar. Back then the reference only carried the title (if any).
Now that the item also can have a title, i should show that one in bold if there's no reference.

**Comment by dankito** [comment]
Fixed it, if there's no reference showing now item's title / summary bold in first line.
