### ISSUE TITLE
Floating button in edit entry screen has different behavior than on the start screen

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#37]
Related to #14 

The behavior of the floating-buttons (in open state) should be the same one as on the start page. Back-button or "tap-anywhere" should close the floating button's sub-buttons.

**Comment by dankito** [comment]
You're right, i forgot the back button, and tapping anywhere else doesn't work reliably.

**Comment by dankito** [comment]
Fixed it now.
