### ISSUE TITLE
Error when adding a new ComputerBase article (since last update 0.2)

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#38]
Before the update, I had added Computerbase to my favorites.
After the last update (version 0.2 ... with new data model?), I could not add new Computerbase entries anymore. Other sources/newspapers worked without any problems.

[Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1M0gyMDFfUVlYR0U)

**Comment by dankito** [comment]
No, it's actually by Computerbase.
It's simply omitting the http status header field (200, 404, ...) and my http library complains about that. And there's no option to turn off this behaviour. Let's see if i can find anything in OkHttp's source code ...

**Comment by dankito** [comment]
Updated now my http library, maybe that fixes it.

**Comment by dankito** [comment]
Never occurred since then anymore, so the library update seems to have fixed it.
