### ISSUE TITLE
Missing thumbnail images in all lists except "Read Later" ?

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#39]
[Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1bTRjeVhpUExPcWc)

I'm not sure, but it looks like that only the Read Later section shows a preview image (thumbnail) for it's enries in the list. Other sections have a lot of space at the left hand side, but don't show an image on my device.

**Also**
An entry, that has a thumbnail image in the read later section does not show a thumbnail image anymore, after it has been "saved/kept" and therefore moved to the Entries/Items section.

**Comment by dankito** [comment]
The difference is
- ReadLaterArticles are articles (how did you that ever figure out, dankito * g *) and therefore almost always have a preview image.
- Items can be anything: Articles but also quotes, thoughts, book excerpts, to dos, ... Most of them don't have a preview image, so there would be a mixed case of items with and items without preview images.

So there's either the option to leave space for a preview image in all items if they have one or not and therefore wasting a lot of space for those which have none, or only showing it for items which have one and then having a mix of items which's text start on the left edge and items showing the image at the left and the text right to it, which may looks kind of odd.

Another difference is items can have tags. Displaying them takes approximately the space of two lines of the content preview. So there is less space for the content in Items list items compared to ReadLaterArticles list item.
Showing additionally a preview image would further reduce the amount of displayed content for an item.
