### ISSUE TITLE
Suggestion: The bold text instead of quotes in the help-messages

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#40]
In most of your help-messages/explainations, you are using single-quotes:
[Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1ekprSUNOMkZtRms)

I would recommend to **not** use quotes, because this looks very unnatural and does not really highlight these words.
In case you would like to highlight some words, I would recommend to make these works **bold** instead. This also should look much better... ;-)

**Comment by dankito** [comment]
Good suggestion, passing it on to my texter.

**Comment by dankito** [comment]
We applied it now as you suggested.
