### ISSUE TITLE
Button in tag's edit page has wrong z index

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#5]
The new/toggle button in the tag's edit page has a wrong z-index in the layout (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1d2FGWW5SU1dhd1k)).

## Expected behavior
The toast message should be in foreground. The toggle button was still in front of the toast message, so I could not close the message.

**Comment by dankito** [comment]
I'd even say the layout totally got messed up *g* (see also the space between the info message and the tag 'Extra').

**Comment by dankito** [comment]
Could reproduce it to 100 %. Issue was that the animation hasn't been set up correctly.
