### ISSUE TITLE
Entry with no title takes a lot of space

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#6]
An item with no title takes a lot of unnecessary space (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1RkQtajZRY2hSZE0) at the top).

### Proposal
Use visibility=Gone when the title/abstract is blank.

**Comment by dankito** [comment]
Not sure how to circumvent this.
Agreed with the designers to give list items a fixed size as we thought showing an item with the height of one text line could look kind of odd in midth all these larger size items.
What would you do, reduce the item height?

**Comment by b3nk4n** [comment]
Actually you are right here. A very small list item looks also awkward here.

**My suggestion:**
I would use a short **fallback-title, in case there is no one given by the user**. The user usually only has to enter a title by himself when he is creating a manual note, right? Web URL / artices always get a title automatically. So how about one of these:

- Thought from _< date of creation >_ (my favorite ... matches to the app title :D )
- Item from _< date of creation >_
- Entry from _< date of creation >_

**Comment by dankito** [comment]
Thought long about it and Evernote does it that way. For notes without a title it displays 'Notiz ohne Title'
But i think there's no use for user in it as it doesn't contain useful information. So i decided against it.
