### ISSUE TITLE
Tags section: "All entries" & "Entries w/o tags" are not clickable

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#7]
This is about these items in the tags section: [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1NHZ6UHRZZDF1Tnc)

The highlighted items are not clickable, even that they show the chevron (>).

### Expected behavior
Either show now chevron when noch clickable, or show a list-page where all / all-untagged articles are listed.

**Comment by dankito** [comment]
You're absolutely right, they have to be clickable (otherwise there would be no use in displayed 'em *g*).

**Comment by dankito** [comment]
Issue was that i wanted to avoid that these two special tags get selected in multi select mode (you cannot edit them), so i disabled clicking on them.
Fixed it now.
