### ISSUE TITLE
Wide icons are rendered squashed

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#8]
I added the NYTimes URL as a new source, but from the variaty of icons I have chones the very wide one (about 30x150px) instead of the other nice square ones.
In the page to add a new NYTimes article, the icon is displayed squashed (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1SUhCYTBmRkpGNWM)) and not uniform.

### Proposed solution
a) Either do not list the wide icon at all, since there are plenty other icons available (filter non-square icons out of the selection of items when there is at least one other "good" icon available, where "good" means it is square and available in reasonable resolution, such as 32x32 or bigger)
b) Show the icon uniformly (non streched)

**Comment by dankito** [comment]
I'd go for option b)
But this will take some time as currently i'm using Toolbar's default icon ImageView - and that is squarish.
Giving it a low priority.

**Comment by dankito** [comment]
Fixed it now by respecting aspect ration when scaling down. But looks curious on real wide icons.

**Comment by dankito** [comment]
Applied now a maximum width, should be fine now.
