### ISSUE TITLE
Sometimes an entry is added twice

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#9]
I cannot really tell how to reproduce it, but sometimes an item appears twice in the list, even that I added it only once:
- [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1VGYzeUk5YmpCYjg)
- [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1aFRhbHhBalpIUG8)

**Comment by b3nk4n** [comment]
Also references sometimes appear twice

**Comment by b3nk4n** [comment]
Here is one way to reproduce a redundant entry in the references section:

1. Open chrome browser
2. Navigate to a page (e.g. an article on Golem.de)
3. Share > DeepThought
4. Press "Save"
5. Check: The entry is only listed once in the "Entries" section
6. Navigate to the the References section
7. Press the reference that was added using Chrome-sharing
8. Check: Now a new page is shown that lists the entry twice!

**But:**
After closing this page and doing all step 5. - 7. again, the entry is only listed once. Same when the app is restarted, then the 2nd entry disappears.

**Comment by b3nk4n** [comment]
One time I thought and entry was saved twice, because I saved it once already (using the save button) and by maybe using the BACK button, I got back to this entry where I could press the save button again. Hence, it was saved a second time? I'm not sure, but at least I had an item in the Entries section twice :)

**Comment by dankito** [comment]
Quite sure this is not a database but an index issue.
As you say navigating away and then back fixes it, so it may be due to the index is written correctly but IndexSearcher doesn't see the update / sees it twice.
Going to investigate on it, high prio.

**Comment by dankito** [comment]
Was a multi threadening issue.
Found a good workaround, but sooner or later will have to implement a async producer-consumer queue in Indexer.
